travis:
  secure:
    BINSTAR_TOKEN: O/VW/H4NmfaJNZe+9eo/oHzBYZ23JRNIQ4B/LFVdjtk5P/fI0XlljFKGbv6RkEc65MR9eFhMoUIFqCaRLxaj1FPD5LYm7LkBdT8utxBPHsdX9edepArEaHSwWHMuj88rhSPg9ciP/lf2b2Vm1VYHTCVHmXk0MvJ6k5hsLxbqyKjtRVdFSHLcUcel6RT14Dm38YQC0pl0WpL5kl64PGJd7OCDvf6V+wtqQBqX0KR2kDyi+60n4rNRG8t1VnOpjsuLkWyTiWyrfYl8mO//HXfjjjr9eEC/Bu60DtJndxrT5o1dnAVacIXU2ZoiTjz1YNdPFvi2SIfTln6Eke+ZwwgMNLCdRsDSx/a9xRblmGq1kcm8+OdNlxwYVfI5rc/qKR6GQMTXApY2umNW59RpkGuVe9D/J1WylYjaoGg94YPcOSQTLNwVgIWucOwWL2zSiYmVuj6iOufEz9NCg2yovPP4vL/hENIA7osya3cLgSMJ6SRZbsgMdyWGupfPEj6S3Dd8ji0mMmtTNcOprUGjH6JVOByfBP6FHEcjvg3nBC67g0nkZ8hjTv/KsfJ/yTc3dLqOoAorhUxgUTrkdCSEPatGn8eeoGDG7IA3mi9XPIlb6txn/rKuocgoyIjV3kRrTZ+QMTXL2lwgzlti5QwFd7v1TAaAwsfexF9qBYbHPhP6+7c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
